import os
import json
import logging
import google.generativeai as genai
from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from pydantic.json_schema import SkipJsonSchema
from typing import List, Optional

from pricing_engine import MaterialIntelligence
from blueprint_engine import BlueprintEngine

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="AI Construction Estimator API")

# Initialize engines
pricing_engine = MaterialIntelligence()
blueprint_engine = BlueprintEngine()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class EstimateRequest(BaseModel):
    prompt: str
    geminiKey: str

@app.post("/api/estimate")
async def generate_estimate(request: EstimateRequest):
    if not request.prompt or not request.geminiKey:
        raise HTTPException(status_code=400, detail="Prompt and Gemini key are required")
        
    try:
        genai.configure(api_key=request.geminiKey)
        model = genai.GenerativeModel("gemini-1.5-flash-latest")
        
        system_prompt = """
        You are an expert general contractor estimator. The user will describe a construction/renovation project.
        You must break down the project into specific rooms/areas.
        For each room, break it down into line items (tasks).
        For each line item, determine:
        1. The necessary materials (Use formal, standard construction terminology).
        2. The required estimated labor hours.
        3. A detailed array of step-by-step instructions for the task.

        Respond ONLY with a valid JSON object strictly matching this schema:
        {
          "rooms": [
            {
              "id": "unique-room-id",
              "name": "Room Name (e.g., Master Bathroom)",
              "lineItems": [
                {
                  "id": "unique-item-id",
                  "taskName": "Task description (e.g., Install Shower Tile)",
                  "laborHours": 8.0,
                  "steps": ["Step 1 description", "Step 2 description", "Step 3 description"],
                  "materials": [
                    {
                      "id": "unique-mat-id",
                      "name": "Name of material (e.g., Ceramic Tile 12x24)",
                      "quantity": 100,
                      "unit": "sqft"
                    }
                  ]
                }
              ]
            }
          ]
        }
        Do not include any other text besides the JSON.
        """
        
        response = model.generate_content(
            request.prompt,
            generation_config=genai.types.GenerationConfig(
                temperature=0.2,
            )
        )
        
        result_text = response.text.strip()
        # Clean markdown codeblocks if they exist
        if result_text.startswith("```json"):
            result_text = result_text[7:]
        if result_text.endswith("```"):
            result_text = result_text[:-3]
            
        result_text = result_text.strip()
        
        try:
            result_json = json.loads(result_text)
        except json.JSONDecodeError:
            logger.error(f"Failed to parse JSON from Gemini: {result_text}")
            raise HTTPException(status_code=500, detail="Invalid JSON generated by AI")

        # Enrich with pricing engine
        for room in result_json.get("rooms", []):
            for item in room.get("lineItems", []):
                for mat in item.get("materials", []):
                    # Check Best Price using the python pricing engine
                    best_price, best_supplier, best_brand, _ = pricing_engine.get_best_price(mat["name"])
                    
                    if best_price != float('inf'):
                        mat["unitCost"] = best_price
                        mat["supplierName"] = best_supplier
                        mat["brandName"] = best_brand
                    else:
                        # Fallback simple pricing mechanism
                        mat["unitCost"] = 15.00
                        mat["supplierName"] = "Unknown"
                        mat["brandName"] = "Generic"
                        
        return result_json
        
    except Exception as e:
        logger.error(f"Error during estimation: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

# Mount static frontend files
FRONTEND_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
app.mount("/", StaticFiles(directory=FRONTEND_DIR, html=True), name="static")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8080)
